#ifndef CONFIG_H
#define CONFIG_H

#define WINDOW_WIDTH 1920
#define WINDOW_HEIGHT 1080
#define FAR_PLANE 1000000.f
#define RANDOM_LIGHT_COUNT 32
#define RANDOM_LIGHT_WITH_SHADOW 4
#define BRIGHTNESS_THRESHOLD_LOWERBOUND 0.001f

#define POINT_LIGHT_SHADOWMAP_RESOLUTION 2048
#define POINT_SHADOW_START_ENABLED false
#define GROUND_YOFFSET (-50.f)

#define BLOOM_THRESHOLD 0.5
#define BLOOM_BOUND_RATIO 0.5
#define BLOOM_SAMPLES 32
#define BLOOM_SIGMA 12
#define BLOOM_STRENGTH 0.1
#define BLOOM_SCALE 1

#define MSAA_ENABLED true
#define MSAA_SAMPLES 4

#endif